on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run: pip install -r requirements.txt
    # - name: Collect static files
    #   run: python manage.py collectstatic
    # - name: Run Tests
    #   env:
    #     FLAKYTEST_SECRET_TOKEN: ${{ secrets.FLAKYTEST_SECRET_TOKEN }}
    #   run: pytest
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          pushd /home/home/projects/djsandbox
          git pull
          . .venv/bin/activate
          pip install -r requirements.txt
          # python manage.py collectstatic --noinput
          # python manage.py migrate
          sudo kill -hup `cat gunicorn.pid`
          echo `date "+%Y-%m-%d %H:%M:%S.%3N"` ' Updated' >> djsandbox_update.log
          popd
